<?php

include_once('extension_find_people.features.inc');



/**
 * Implementation of hook_init().
 */
function extension_find_people_init() {
  drupal_add_css(drupal_get_path('module', 'extension_find_people') .'/theme/extension_find_people.css');
}

/**
 * Implementation of hook_theme().
 */
 
function extension_find_people_preprocess_node(&$variables) {
  if ($variables['node']->type == 'employee') {
    $variables['template_file'] = 'employee';
  }
  if ($variables['node']->type == 'group') {
    $variables['template_file'] = 'group';
  }
}

/**
 * Implementation of hook_theme_registry_alter().
 */
function extension_find_people_theme_registry_alter(&$theme_registry) {
  $modulepath = drupal_get_path('module', 'extension_find_people') . '/theme';
  array_unshift($theme_registry[node]['theme paths'], $modulepath);
}



/**
* Implementation of hook_form_alter().
*/
function extension_find_people_form_alter(&$form, $form_state, $form_id) {

  switch ($form_id) {
    case 'employee_node_form':
      // $output .= dsm($form);
      
      // unset delete button for non-admins
      global $user;
      if (!in_array('administrator', array_values($user->roles))) { 
        unset($form['buttons']['delete']);
      }
    break;
  }
}